#ifndef atRibbonH
#define atRibbonH
#include "atExplorerObject.h"
#include "atSections.h"
//---------------------------------------------------------------------------

namespace at
{

//!The ribbon class abstracts an AT Ribbon..
//!A Ribbon is a list of consecutive sections
class ATE_DATA Ribbon : public Sections
{
    public:
                        Ribbon(int id, const string& alias = "");
        virtual         ~Ribbon();
        bool            clear();
        void            assignLongRibbonID(const string& lid);

        string          getAlias(){return mAlias;}
        int		        getShortRibbonID(){return mShortRibbonID;}
        string          getLongRibbonID(){return mLongRibbonID;}

        int             sectionCount();
        void            appendSection(Section* sec);

    protected:

                        //!Within a data set, each ribbon have a short and long ID
        int             mShortRibbonID;

                        //!This id is generated by the microtome and logged in ATDB
        string          mLongRibbonID;

                        //!Alias can be used to refer original data folders, names etc..
        string          mAlias;
};

}


#endif
